config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: :callbacks}

  # get "/profile", to: "users#show", as: "user"
  resources :users, only: %i[show]

  root "tweets#index"

  resources :likes
  resources :tweets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
  # validations
  validates :user, uniqueness: { scope: :tweet, message: "and Tweet combination already taken" }
  # associations
  belongs_to :user
  belongs_to :tweet, counter_cache: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  # Associations
  belongs_to :user
  belongs_to :replied_to, class_name: "Tweet", optional: true, counter_cache: :replies_count
  has_many :threads, class_name: "Tweet", foreign_key: "replied_to_id",
            inverse_of: "replied_to", dependent: :nullify
  has_many :likes, dependent: :destroy

  # Validations
  validates :body, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  # validations
  validates :username, presence: true, uniqueness: true
  validates :name, presence: true

  has_one_attached :avatar
  # Associations
  has_many :tweets, dependent: :nullify
  has_many :likes, dependent: :destroy
  # has_many :tweets, through: :likes

  # enum
  enum role: { member: 0,
               admin: 1}
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.username = auth.info.name
      user.name = auth.info.name
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: %i[index show]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :avatar])
  end

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action"
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def github
    auth_hash = request.env["omniauth.auth"]
    @user = User.from_omniauth(auth_hash)
    sign_in_and_redirect @user
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like, only: %i[ show edit update destroy ]

  # GET /likes
  def index
    @likes = Like.all
  end

  # GET /likes/1
  def show
  end

  # GET /likes/new
  def new
    @like = Like.new
  end

  # GET /likes/1/edit
  def edit
  end

  # POST /likes
  def create
    @like = Like.new(like_params)

    if @like.save
      redirect_back_or_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /likes/1
  def update
    if @like.update(like_params)
      redirect_to @like, notice: "Like was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /likes/1
  def destroy
    @like.destroy
    redirect_to likes_url, notice: "Like was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_like
      @like = Like.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def like_params
      params.require(:like).permit(:user_id, :tweet_id)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]

  # GET /tweets
  def index
    @tweets = Tweet.where(replied_to: nil).order(updated_at: :desc)
  end

  # GET /tweets/1
  def show
    @current_tweet = Tweet.find(params[:id]).threads.new(user: current_user)
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  def create
    @tweet = Tweet.new(tweet_params)

    if @tweet.save
      redirect_to tweet_path(@current_tweet = Tweet.find(params[:id]).threads.new(user: current_user))
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /tweets/1
  def update
    if @tweet.update(tweet_params)
      redirect_to @tweet, notice: "Tweet was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /tweets/1
  def destroy
    @tweet.destroy
    redirect_to root_path, notice: "Tweet was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:body, :replies_count, :likes_count, :user_id, :replied_to_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show]

  def show
    @user = set_user
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def time_ago_in_words(from_time, include_seconds_or_options = {})
    distance_of_time_in_words(from_time, Time.zone.now, include_seconds_or_options)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweetable</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">
  </head>
  <body class="background">

    <header>
      <div class="container-lg">
        <nav class="nav__tweet">
          <%= link_to root_path, class:"text-decoration-none" do %>
            <span class="title">Tweet</span>
          <% end %>
          <input type="checkbox" id="menu-mobile" >
          <label for="menu-mobile" id="toogle-close"  >
            <i class="ri-close-line "></i>
          </label>
          <label for="menu-mobile" id="toogle-open" >
            <i class="ri-menu-line"></i>
          </label>
          <!-- <label for="menu-mobile" id="toogle-open">a</label> -->
          <ul class="nav--links expandable">
            <li>
            <% if current_user%>
              <p><%=current_user.username%> </p>
            <% end %>
            </li>
            <li><%= link_to "Tweets", root_path, class: "link text-sm" %>
          <% if current_user %>
            <li><%=link_to "Profile", user_path(current_user), class:"link text-sm" %></li>
            <li><%=button_to "Log Out", destroy_user_session_path, :method=> :delete, class:"button button--secondary button--sm" %></li>
          <% else %>
            <li><%=button_to "Log In", new_user_session_path, :method => :get, class:"button button--primary button--sm" %></li>
          <% end %>  
          </ul>
        </nav>
      </div>
  
    </header>
    <br>

    <% if alert %>
      <div class = "alert_not_logged_in">
        <p><%= alert %></p>
        <%= link_to "Sign in", new_user_session_path , class: " button text-decoration-none button--primary" %>
      </div>
    <% end %>

    <%# end alerts %>
    <%= yield %>

    <footer class="footer_content">
      <div>
      <p>© 2021 - Codeable Tweetable</p>
      <p>Build with ♥ by</p>
      <div class="footer_content2"> 
        <div>
            <div class="container__svg">
              <svg><use xlink:href="#in"></svg>
            </div>
            <p>student Name</p>
        </div>
        <div>
            <div class="container__svg">
              <svg><use xlink:href="#in"></svg>
            </div>
            <p>student Name</p>
        </div>
        <div>
            <div class="container__svg">
              <svg><use xlink:href="#in"></svg>
            </div>
            <p>student Name</p>
        </div>
      </div>

      <div class="footer_content2"> 
        <div>
            <div class="container__svg">
              <svg><use xlink:href="#in"></svg>
            </div>
            <p>student Name</p>
        </div>
        <div>
            <div class="container__svg">
              <svg><use xlink:href="#in"></svg>
            </div>
            <p>student Name</p>
        </div>
      </div>
      


      </div>
    </footer>

    <div hidden>
      <svg xmlns="http://www.w3.org/2000/svg">
        <symbol id="in" width="20" height="20" viewBox="0 0 18 18">
          <path d="M0.666667 0H11.3333C11.5101 0 11.6797 0.0702379 11.8047 0.195262C11.9298 0.320286 12 0.489856 12 0.666667V11.3333C12 11.5101 11.9298 11.6797 11.8047 11.8047C11.6797 11.9298 11.5101 12 11.3333 12H0.666667C0.489856 12 0.320286 11.9298 0.195262 11.8047C0.0702379 11.6797 0 11.5101 0 11.3333V0.666667C0 0.489856 0.0702379 0.320286 0.195262 0.195262C0.320286 0.0702379 0.489856 0 0.666667 0ZM1.33333 1.33333V10.6667H10.6667V1.33333H1.33333ZM3 4C2.73478 4 2.48043 3.89464 2.29289 3.70711C2.10536 3.51957 2 3.26522 2 3C2 2.73478 2.10536 2.48043 2.29289 2.29289C2.48043 2.10536 2.73478 2 3 2C3.26522 2 3.51957 2.10536 3.70711 2.29289C3.89464 2.48043 4 2.73478 4 3C4 3.26522 3.89464 3.51957 3.70711 3.70711C3.51957 3.89464 3.26522 4 3 4ZM2.33333 4.66667H3.66667V9.66667H2.33333V4.66667ZM6 4.95333C6.38933 4.57667 6.844 4.33333 7.33333 4.33333C8.714 4.33333 9.66667 5.45267 9.66667 6.83333V9.66667H8.33333V6.83333C8.33333 6.52391 8.21042 6.22717 7.99162 6.00838C7.77283 5.78958 7.47609 5.66667 7.16667 5.66667C6.85725 5.66667 6.5605 5.78958 6.34171 6.00838C6.12292 6.22717 6 6.52391 6 6.83333V9.66667H4.66667V4.66667H6V4.95333Z" fill="#303036"/>
        </symbol>
      </svg>
    </div>
  </body>
</html>

app/views/likes/_form.html.erb
<%= form_with(model: like) do |form| %>
  <% if like.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(like.errors.count, "error") %> prohibited this like from being saved:</h2>

      <ul>
        <% like.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div hidden>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div hidden>
    <%= form.label :tweet_id, style: "display: block" %>
    <%= form.text_field :tweet_id %>
  </div>

  <div id=""><p>
    <%= image_submit_tag("dont_like_icon.png") %></p>
    <%=  %>
  </div>

<% end %>

app/views/likes/_like.html.erb
<div id="<%= dom_id like %>">
  <p>
    <strong>User:</strong>
    <%= like.user_id %>
  </p>

  <p>
    <strong>Tweet:</strong>
    <%= like.tweet_id %>
  </p>

</div>

app/views/likes/edit.html.erb
<h1>Editing like</h1>

<%= render "form", like: @like %>

<br>

<div>
  <%= link_to "Show this like", @like %> |
  <%= link_to "Back to likes", likes_path %>
</div>

app/views/likes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Likes</h1>

<div id="likes">
  <% @likes.each do |like| %>
    <%= render like %>
    <p>
      <%= link_to "Show this like", like %>
    </p>
  <% end %>
</div>

<%= link_to "New like", new_like_path %>

app/views/likes/new.html.erb
<h1>New like</h1>

<%= render "form", like: @like %>

<br>

<div>
  <%= link_to "Back to likes", likes_path %>
</div>

app/views/likes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @like %>

<div>
  <%= link_to "Edit this like", edit_like_path(@like) %> |
  <%= link_to "Back to likes", likes_path %>

  <%= button_to "Destroy this like", @like, method: :delete %>
</div>

app/views/tweets/_card.html.erb
<div class="card p-card">

  <%= link_to tweet.user do%>
    <div class="card__head">
      <div>
        <% if tweet.user.avatar.attached? %>
            <%= image_tag tweet.user.avatar, class: "index--img" %>
        <% else %>
            <%= image_tag("avatar_default.jpg", class: "index--img") %>
        <% end %>
      </div>

      <div class="link text-left">
        <div>
          <span class="name" ><%= tweet.user.name %></span>
          <span class=""username>@<%= tweet.user.username %></span>
        </div>

        <span class="times_ago">
          <%= time_ago_in_words(tweet.updated_at) %>
          ago 
        </span>
      </div>
    </div>
  <% end %>

  <div class="card_body">
    <%= link_to tweet do%>
      <div>
        <p class="text_body content-sm link text-left"><%= tweet.body %></p>
      </div>
    <% end %>


    <div class="flex justify-between">

      <div class="flex gap-4">
        <% if current_user == tweet.user %>
          <%= link_to image_tag("destroy.png"), tweet_path(tweet),
            data: {turbo_method: :delete} %>
          <%#= link_to edit_tweet_path(tweet) do%>
            <%#= image_tag("destroy.png")%>
          <%# end %>

          <%= link_to edit_tweet_path(tweet) do%>
            <%= image_tag("edit.png")%>
          <% end %>
        <% end %>
      </div>

      <div class="flex gap-4">
          <%= link_to tweet do%>
            <%= image_tag("comment_icon.png")%>
          <% end %>

      <%# button like enabled or disabled : Yhostin %>
      <% like = current_user.likes.find{ |l| l.tweet == tweet} if current_user %>
      <% unless !!like %>
        <%= render "likes/form", like: tweet.likes.new(user:current_user) %>
      <% else %>
       <%= link_to like_path(like), method: "delete",
            data: { turbo_method: :delete, turbo_confirm: 'Are you sure dislike tweet?' } do%>
            <%= image_tag("like_icon.png")%>
        <% end %>
      <% end %>
      </div>

    </div>
  </div>
</div>

app/views/tweets/_form.html.erb
<div class="tweet">
  <%= form_with(model: tweet) do |form| %>
    <% if tweet.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

        <ul>
          <% tweet.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <% if current_user %>
      <div hidden>
        <%= form.label :user_id %>
        <%= form.text_field :user_id, value: current_user.id %>
      </div>
    <%end%>
    <div hidden>
      <%= form.label :replied_to_id %>
      <%= form.text_field :replied_to_id %>
    </div>

    <div class="text-area">
      <%= form.text_area :body, class:"text-area--form" %>
    </div>

    <div class="bg-white text-right">
      <%= form.submit "Tweet", class: "button_tweet button--sm" %>
    </div>
  <% end %>
</div>

app/views/tweets/_tweet.html.erb
<div id="<%= dom_id tweet %>", class="card">
  <div class="card__head">
    <div>
      <% if tweet.user.avatar.attached? %>
        <div>
          <%= image_tag tweet.user.avatar, class: "index--img" %>
        </div>
      <% end %>
    </div>

    <div>
      <div>
        <span class="name" ><%= tweet.user.name %></span>
        <span class=""username>@<%= tweet.user.username %></span>
      </div>

      <span class="times_ago">
        <%= time_ago_in_words(tweet.updated_at) %> ago
      </span>
    </div>
  </div>

  <p>
    <%= tweet.body %>
  </p>
  
  <div class="card__body--icons">
    <div class="flex_icons" >
      <div >
        <%= link_to edit_tweet_path(tweet) do%>
          <%= image_tag("comment_icon.png")%>
        <% end %>
      </div>
      <div>
        <span><%= tweet.threads.count %></span>
      </div>
    </div>

    <div class="flex_icons">
      <div>
        <%= render "likes/form", like: tweet.likes.new(user:current_user) %>
      </div>
      <div>
        <span><%= tweet.likes.count %></span>
      </div>  
    </div>
  </div>

</div>

app/views/tweets/edit.html.erb
<h1 class="mb-4 text-center">Edit tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Show this tweet", @tweet %> |
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="section-sm">
  <div class="container-sm center">
    <h1 class="text-center mb-4">Home</h1>

    <%# Box to create tweet %>


    <div id="tweets">

      <%= render "tweets/form", {tweet: Tweet.new} %>
      <% @tweets.each do |tweet| %>        
        <%= render "card", tweet: tweet, user: current_user%>   
      <% end %>

    </div>
  </div>
</div>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/show.html.erb
<p style="color: green"><%= notice %></p>
<h2 class="text-center mb-4">Tweet Detail</h2>
<%= render @tweet %>
<hr>

<div id="tweets">

  <%= render "tweets/form", {tweet: @current_tweet} %>
  <% @tweet.threads.each do |tweet| %>
    <%= link_to tweet do%>
      <%= render "card", tweet: tweet%>
    <% end %>
  <% end %>

</div>


<div>
  <%= link_to "Edit this tweet", edit_tweet_path(@tweet) %> |
  <%= link_to "Back to tweets", tweets_path %>

  <%= button_to "Destroy this tweet", @tweet, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :birth_date, style: "display: block" %>
    <%= form.date_field :birth_date %>
  </div>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
 <%# User profile %>

<div id="<%= dom_id user %>">

  <h1 class=" heading--sm">Profile</h1>
  <% if user.avatar.attached? %>
    <%= image_tag(user.avatar, class: "image_circle_lg") %>
  <% else %>
    <%= image_tag("avatar_default.jpg", class: "image_circle_lg") %>
  <% end %>
  
  <div class="flex flex-column text-center ">
    <span><%= user.name %></span>
    <span>@<%= user.username %></span>
    <span class="">Joined on <%= user.created_at.strftime('%d, %Y') %></span>
  </div>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<section class="section-md">
  <div class="">


    <div class="flex flex-column wrap text-center items-center mb-4">
      <%= render @user %>
      <%# Add polices: to view button edit profile %>
      
      <% if current_user == @user%>
        <%=button_to "Edit Profile", edit_user_registration_path(@user), method: :get, class: "button button--primary mb-4" %>
      <% end %>
      <%# end polices %>

    </div>

    <div>
      <h2 class="mb-4 text-center">Tweets (<%= @user.tweets.count %>)</h2>
      <% @user.tweets.each do |tweet| %>
        <%= render "/tweets/card", tweet: tweet%> 
      <% end %>
    </div>

    <div>
      <h2 class="mb-4 text-center">Likes (<%= @user.likes.count %>)</h2>
      <% @user.likes.each do |like| %>
        <%= render "/tweets/card", tweet: like.tweet%> 
      <% end %>
    </div>
  </div>
</section>

  <div hidden>
    <div>
      <svg><use xlink:href="#destroy"></svg>
      <svg><use xlink:href="#edit"></svg>
    </div>
    <div>
      <svg><use xlink:href="#comment"></svg>
      <svg><use xlink:href="#like"></svg>
    </div> 
  </div>
  <div hidden>
    <svg  xmlns="http://www.w3.org/2000/svg" >
      <symbol id = "destroy" viewBox="0 0 18 20">
        <path d="M16 5L15.1327 17.1425C15.0579 18.1891 14.187 19 13.1378 19H4.86224C3.81296 19 2.94208 18.1891 2.86732 17.1425L2 5M7 9V15M11 9V15M12 5V2C12 1.44772 11.5523 1 11 1H7C6.44772 1 6 1.44772 6 2V5M1 5H17" stroke="#7A7A7A" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
       </symbol>
    </svg>

    <svg  xmlns="http://www.w3.org/2000/svg" >
      <symbol id = "edit" viewBox="0 0 19 19">
        <path d="M8 3H3C1.89543 3 1 3.89543 1 5V16C1 17.1046 1.89543 18 3 18H14C15.1046 18 16 17.1046 16 16V11M14.5858 1.58579C15.3668 0.804738 16.6332 0.804738 17.4142 1.58579C18.1953 2.36683 18.1953 3.63316 17.4142 4.41421L8.82842 13H6L6 10.1716L14.5858 1.58579Z" stroke="#7A7A7A" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
       </symbol>
    </svg>

    <svg  xmlns="http://www.w3.org/2000/svg" >
      <symbol id = "comment" viewBox="0 0 20 18">
      <path d="M6 9H6.01M10 9H10.01M14 9H14.01M19 9C19 13.4183 14.9706 17 10 17C8.46073 17 7.01172 16.6565 5.74467 16.0511L1 17L2.39499 13.28C1.51156 12.0423 1 10.5743 1 9C1 4.58172 5.02944 1 10 1C14.9706 1 19 4.58172 19 9Z" stroke="#7A7A7A" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
       </symbol>
    </svg>

    <svg  xmlns="http://www.w3.org/2000/svg" >
      <symbol id = "like" viewBox="0 0 20 18">
        <path d="M2.31802 2.31802C0.56066 4.07538 0.56066 6.92462 2.31802 8.68198L10.0001 16.364L17.682 8.68198C19.4393 6.92462 19.4393 4.07538 17.682 2.31802C15.9246 0.56066 13.0754 0.56066 11.318 2.31802L10.0001 3.63609L8.68198 2.31802C6.92462 0.56066 4.07538 0.56066 2.31802 2.31802Z" stroke="#7A7A7A" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
       </symbol>
    </svg>
  </div>